### ISSUE TITLE
Fix security issue with cleartext passwords in shell history

### ISSUE THREAD

**Issue by pushfoo** [aspizu/neocities-sync#2]
**TL;DR:** The current flags-based credential options leave cleartext passwords in shell history

For example, the `--password cleartext_here` flag will leave `cleartext_here` in the shell history.

Pulling from environment variables would be a mild improvement, but using a system credentials storage API would be best.

**Comment by aspizu** [comment]
I can't seem to find any node packages to deal with credentials on linux (<https://github.com/atom/node-keytar> exists but it is archived)
